### PR TITLE
user acess update for admin panel

### PR DESCRIPTION
**Pull request by usmandap**

### CODE REVIEW

**Comment by usmandap** [comment]
@mashhoodr I am unable get these codacy issues, could you please have a look.

**Comment by abdulmoizeng** [comment]
@usmandap , see following https://kite.com/python/docs/django.contrib.admin.options.ModelAdmin.formfield_for_foreignkey

You are using `(self, db_field, request, **kwargs)` just remove `self` and it should work.

 Please use `db_field, request, **kwargs` and confirm

**Comment by usmandap** [comment]
@abdulmoizeng Your solution didn't worked for me getting error `formfield_for_foreignkey() takes 2 positional arguments but 3 were given`.

**Comment by usmandap** [comment]
@mashhoodr I am unable to find any solution so I have currently disabled these codacy errors.

**Pull request merged**
